# Generated by Django 2.2.3 on 2019-07-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_ideia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideia',
            name='categorias_outros',
        ),
        migrations.AddField(
            model_name='ideia',
            name='categoria_outros',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caso outros, qual?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='', max_length=200, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default='', max_length=255, verbose_name='Senha'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ideia',
            name='titulo',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nome de ideia'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=50, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='sobrenome',
            field=models.CharField(max_length=100, verbose_name='Sobrenome'),
        ),
    ]
